'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class lang_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Planned_shutdown.lang_en", GetType(lang_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à About.
        '''</summary>
        Friend Shared ReadOnly Property about() As String
            Get
                Return ResourceManager.GetString("about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancel() As String
            Get
                Return ResourceManager.GetString("cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel the computer shutdown.
        '''</summary>
        Friend Shared ReadOnly Property cancel_shutdown_btn() As String
            Get
                Return ResourceManager.GetString("cancel_shutdown_btn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The software cannot connect to the server!.
        '''</summary>
        Friend Shared ReadOnly Property cannot_connect() As String
            Get
                Return ResourceManager.GetString("cannot_connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Changelog.
        '''</summary>
        Friend Shared ReadOnly Property changelog() As String
            Get
                Return ResourceManager.GetString("changelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Check updates.
        '''</summary>
        Friend Shared ReadOnly Property chkupdt_btn() As String
            Get
                Return ResourceManager.GetString("chkupdt_btn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choose action.
        '''</summary>
        Friend Shared ReadOnly Property choose_action() As String
            Get
                Return ResourceManager.GetString("choose_action", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Developed by MisterEvans78.
        '''</summary>
        Friend Shared ReadOnly Property dev_by() As String
            Get
                Return ResourceManager.GetString("dev_by", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Download.
        '''</summary>
        Friend Shared ReadOnly Property download() As String
            Get
                Return ResourceManager.GetString("download", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Please enter a time!.
        '''</summary>
        Friend Shared ReadOnly Property enter_time() As String
            Get
                Return ResourceManager.GetString("enter_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Fast boot.
        '''</summary>
        Friend Shared ReadOnly Property fast_boot() As String
            Get
                Return ResourceManager.GetString("fast_boot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Input a time.
        '''</summary>
        Friend Shared ReadOnly Property input_time() As String
            Get
                Return ResourceManager.GetString("input_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à English.
        '''</summary>
        Friend Shared ReadOnly Property lang_english() As String
            Get
                Return ResourceManager.GetString("lang_english", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à French.
        '''</summary>
        Friend Shared ReadOnly Property lang_french() As String
            Get
                Return ResourceManager.GetString("lang_french", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Portuguese.
        '''</summary>
        Friend Shared ReadOnly Property lang_portuguese() As String
            Get
                Return ResourceManager.GetString("lang_portuguese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Language:.
        '''</summary>
        Friend Shared ReadOnly Property language_text() As String
            Get
                Return ResourceManager.GetString("language_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à What do you want to do?.
        '''</summary>
        Friend Shared ReadOnly Property main_question() As String
            Get
                Return ResourceManager.GetString("main_question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A new update of the software is available..
        '''</summary>
        Friend Shared ReadOnly Property new_update_text() As String
            Get
                Return ResourceManager.GetString("new_update_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à New update available!.
        '''</summary>
        Friend Shared ReadOnly Property new_update_title() As String
            Get
                Return ResourceManager.GetString("new_update_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à OK.
        '''</summary>
        Friend Shared ReadOnly Property ok() As String
            Get
                Return ResourceManager.GetString("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Options.
        '''</summary>
        Friend Shared ReadOnly Property options() As String
            Get
                Return ResourceManager.GetString("options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Please wait....
        '''</summary>
        Friend Shared ReadOnly Property please_wait() As String
            Get
                Return ResourceManager.GetString("please_wait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Reboot.
        '''</summary>
        Friend Shared ReadOnly Property reboot() As String
            Get
                Return ResourceManager.GetString("reboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The service is currently not available!.
        '''</summary>
        Friend Shared ReadOnly Property service_not_available() As String
            Get
                Return ResourceManager.GetString("service_not_available", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Shutdown.
        '''</summary>
        Friend Shared ReadOnly Property shutdown() As String
            Get
                Return ResourceManager.GetString("shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Plan the computer shutdown.
        '''</summary>
        Friend Shared ReadOnly Property shutdown_btn() As String
            Get
                Return ResourceManager.GetString("shutdown_btn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you want to cancel the planned shutdown?.
        '''</summary>
        Friend Shared ReadOnly Property shutdown_question() As String
            Get
                Return ResourceManager.GetString("shutdown_question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Dark.
        '''</summary>
        Friend Shared ReadOnly Property theme_dark() As String
            Get
                Return ResourceManager.GetString("theme_dark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Light.
        '''</summary>
        Friend Shared ReadOnly Property theme_light() As String
            Get
                Return ResourceManager.GetString("theme_light", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Black theme.
        '''</summary>
        Friend Shared ReadOnly Property theme_superdark() As String
            Get
                Return ResourceManager.GetString("theme_superdark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à System.
        '''</summary>
        Friend Shared ReadOnly Property theme_system() As String
            Get
                Return ResourceManager.GetString("theme_system", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Theme:.
        '''</summary>
        Friend Shared ReadOnly Property theme_text() As String
            Get
                Return ResourceManager.GetString("theme_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Planned shutdown.
        '''</summary>
        Friend Shared ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update.
        '''</summary>
        Friend Shared ReadOnly Property update() As String
            Get
                Return ResourceManager.GetString("update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Update available.
        '''</summary>
        Friend Shared ReadOnly Property update_available() As String
            Get
                Return ResourceManager.GetString("update_available", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Check update at startup.
        '''</summary>
        Friend Shared ReadOnly Property update_chkbox() As String
            Get
                Return ResourceManager.GetString("update_chkbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à No new update is available..
        '''</summary>
        Friend Shared ReadOnly Property updated() As String
            Get
                Return ResourceManager.GetString("updated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Version.
        '''</summary>
        Friend Shared ReadOnly Property version() As String
            Get
                Return ResourceManager.GetString("version", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
