'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class lang_fr
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Planned_shutdown.lang_fr", GetType(lang_fr).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à À propos.
        '''</summary>
        Friend Shared ReadOnly Property about() As String
            Get
                Return ResourceManager.GetString("about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler.
        '''</summary>
        Friend Shared ReadOnly Property cancel() As String
            Get
                Return ResourceManager.GetString("cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Annuler l&apos;arrêt de l&apos;ordinateur.
        '''</summary>
        Friend Shared ReadOnly Property cancel_shutdown_btn() As String
            Get
                Return ResourceManager.GetString("cancel_shutdown_btn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Impossible de se connecter au serveur !.
        '''</summary>
        Friend Shared ReadOnly Property cannot_connect() As String
            Get
                Return ResourceManager.GetString("cannot_connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Changelog.
        '''</summary>
        Friend Shared ReadOnly Property changelog() As String
            Get
                Return ResourceManager.GetString("changelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vérifier mises à jours.
        '''</summary>
        Friend Shared ReadOnly Property chkupdt_btn() As String
            Get
                Return ResourceManager.GetString("chkupdt_btn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choisir une action.
        '''</summary>
        Friend Shared ReadOnly Property choose_action() As String
            Get
                Return ResourceManager.GetString("choose_action", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Développé par MisterEvans78.
        '''</summary>
        Friend Shared ReadOnly Property dev_by() As String
            Get
                Return ResourceManager.GetString("dev_by", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Télécharger.
        '''</summary>
        Friend Shared ReadOnly Property download() As String
            Get
                Return ResourceManager.GetString("download", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez entrer un temps !.
        '''</summary>
        Friend Shared ReadOnly Property enter_time() As String
            Get
                Return ResourceManager.GetString("enter_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Démarrage rapide.
        '''</summary>
        Friend Shared ReadOnly Property fast_boot() As String
            Get
                Return ResourceManager.GetString("fast_boot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Saisir un temps.
        '''</summary>
        Friend Shared ReadOnly Property input_time() As String
            Get
                Return ResourceManager.GetString("input_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Anglais.
        '''</summary>
        Friend Shared ReadOnly Property lang_english() As String
            Get
                Return ResourceManager.GetString("lang_english", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Français.
        '''</summary>
        Friend Shared ReadOnly Property lang_french() As String
            Get
                Return ResourceManager.GetString("lang_french", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Portugais.
        '''</summary>
        Friend Shared ReadOnly Property lang_portuguese() As String
            Get
                Return ResourceManager.GetString("lang_portuguese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Langue :.
        '''</summary>
        Friend Shared ReadOnly Property language_text() As String
            Get
                Return ResourceManager.GetString("language_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Que voulez-vous faire ?.
        '''</summary>
        Friend Shared ReadOnly Property main_question() As String
            Get
                Return ResourceManager.GetString("main_question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Une nouvelle version du logiciel est disponible..
        '''</summary>
        Friend Shared ReadOnly Property new_update_text() As String
            Get
                Return ResourceManager.GetString("new_update_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Nouvelle mise à jour disponible !.
        '''</summary>
        Friend Shared ReadOnly Property new_update_title() As String
            Get
                Return ResourceManager.GetString("new_update_title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à OK.
        '''</summary>
        Friend Shared ReadOnly Property ok() As String
            Get
                Return ResourceManager.GetString("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Options.
        '''</summary>
        Friend Shared ReadOnly Property options() As String
            Get
                Return ResourceManager.GetString("options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Veuillez patienter....
        '''</summary>
        Friend Shared ReadOnly Property please_wait() As String
            Get
                Return ResourceManager.GetString("please_wait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Redémarrer.
        '''</summary>
        Friend Shared ReadOnly Property reboot() As String
            Get
                Return ResourceManager.GetString("reboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Le service n&apos;est actuellement pas disponible !.
        '''</summary>
        Friend Shared ReadOnly Property service_not_available() As String
            Get
                Return ResourceManager.GetString("service_not_available", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Arrêter.
        '''</summary>
        Friend Shared ReadOnly Property shutdown() As String
            Get
                Return ResourceManager.GetString("shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Planifier l&apos;arrêt de l&apos;ordinateur.
        '''</summary>
        Friend Shared ReadOnly Property shutdown_btn() As String
            Get
                Return ResourceManager.GetString("shutdown_btn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Voulez-vous annuler l&apos;arrêt planifié ?.
        '''</summary>
        Friend Shared ReadOnly Property shutdown_question() As String
            Get
                Return ResourceManager.GetString("shutdown_question", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sombre.
        '''</summary>
        Friend Shared ReadOnly Property theme_dark() As String
            Get
                Return ResourceManager.GetString("theme_dark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Clair.
        '''</summary>
        Friend Shared ReadOnly Property theme_light() As String
            Get
                Return ResourceManager.GetString("theme_light", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Thème noir.
        '''</summary>
        Friend Shared ReadOnly Property theme_superdark() As String
            Get
                Return ResourceManager.GetString("theme_superdark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Système.
        '''</summary>
        Friend Shared ReadOnly Property theme_system() As String
            Get
                Return ResourceManager.GetString("theme_system", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Thème :.
        '''</summary>
        Friend Shared ReadOnly Property theme_text() As String
            Get
                Return ResourceManager.GetString("theme_text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Arrêt planifié.
        '''</summary>
        Friend Shared ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mise à jour disponible.
        '''</summary>
        Friend Shared ReadOnly Property update_available() As String
            Get
                Return ResourceManager.GetString("update_available", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vérifier mises à jours au démarrage.
        '''</summary>
        Friend Shared ReadOnly Property update_chkbox() As String
            Get
                Return ResourceManager.GetString("update_chkbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aucune nouvelle mise à jour n&apos;est disponible..
        '''</summary>
        Friend Shared ReadOnly Property updated() As String
            Get
                Return ResourceManager.GetString("updated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Version.
        '''</summary>
        Friend Shared ReadOnly Property version() As String
            Get
                Return ResourceManager.GetString("version", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
